# Generated by Django 5.0.2 on 2024-02-23 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("api", "0001_initial"),
        ("api", "0002_alter_mesh_date_created"),
        ("api", "0003_gallery_meshimage_alter_mesh_options_alter_mesh_mesh_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Фото модели",
                "verbose_name_plural": "Фото моделей",
            },
        ),
        migrations.CreateModel(
            name="MeshImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        unique=True, upload_to="images/", verbose_name="Фото"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Имя")),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "mesh",
                    models.FileField(
                        blank=True, null=True, upload_to="mesh/", verbose_name="Файл"
                    ),
                ),
                (
                    "gallery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.gallery",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="images",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.meshimage",
                to_field="src",
                verbose_name="Фотографии",
            ),
        ),
    ]
