# Generated by Django 5.0.2 on 2024-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Имя")),
                ("date_created", models.DateTimeField(verbose_name="Создано")),
                ("mesh", models.FileField(upload_to="", verbose_name="Файл")),
            ],
        ),
    ]
