# Generated by Django 5.0.2 on 2024-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mesh",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
    ]
