# Generated by Django 5.0.2 on 2024-03-02 01:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0001_initial_squashed_0003_gallery_meshimage_alter_mesh_options_alter_mesh_mesh_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "file",
                    models.ImageField(
                        upload_to=api.models.image_upload_path, verbose_name="image"
                    ),
                ),
            ],
        ),
    ]
