# Generated by Django 5.0.2 on 2024-03-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_imageupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageUpload",
        ),
        migrations.AlterField(
            model_name="gallery",
            name="images",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.meshimage",
                verbose_name="Фотографии",
            ),
        ),
        migrations.AlterField(
            model_name="meshimage",
            name="src",
            field=models.ImageField(upload_to="images/", verbose_name="Фото"),
        ),
    ]
