# Generated by Django 5.0.2 on 2024-03-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_imageupload_alter_gallery_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="images",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.meshimage",
                verbose_name="Фотографии",
            ),
        ),
    ]
