# Generated by Django 5.0.2 on 2024-03-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_gallery_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="images",
        ),
        migrations.AddField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(
                null=True, to="api.meshimage", verbose_name="Фотографии"
            ),
        ),
    ]
